/** Кот Гамбит — Tailwind-конфиг, редакция 2. Цвета из CSS-переменных (tokens.css): тема переключается data-theme на <html>. */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    screens: { tablet: '768px', laptop: '1024px', desktop: '1440px' },
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-2': 'var(--color-surface-2)',
        line: 'var(--color-line)',
        'line-strong': 'var(--color-line-strong)',
        text: 'var(--color-text)',
        'text-2': 'var(--color-text-2)',
        'text-muted': 'var(--color-text-muted)',
        brand: 'var(--color-brand)',
        'brand-depth': 'var(--color-brand-depth)',
        'brand-tint': 'var(--color-brand-tint)',
        'brand-tint-depth': 'var(--color-brand-tint-depth)',
        'brand-text': 'var(--color-brand-text)',
        'on-brand': 'var(--color-on-brand)',
        sun: 'var(--color-sun)',
        'sun-depth': 'var(--color-sun-depth)',
        'sun-tint': 'var(--color-sun-tint)',
        'sun-text': 'var(--color-sun-text)',
        'sun-border': 'var(--color-sun-border)',
        mint: 'var(--color-mint)',
        'mint-depth': 'var(--color-mint-depth)',
        'mint-tint': 'var(--color-mint-tint)',
        'mint-text': 'var(--color-mint-text)',
        'mint-border': 'var(--color-mint-border)',
        coral: 'var(--color-coral)',
        'coral-depth': 'var(--color-coral-depth)',
        'coral-tint': 'var(--color-coral-tint)',
        'coral-text': 'var(--color-coral-text)',
        'coral-border': 'var(--color-coral-border)',
        flame: 'var(--color-flame)',
        'flame-depth': 'var(--color-flame-depth)',
        'flame-tint': 'var(--color-flame-tint)',
        'flame-text': 'var(--color-flame-text)',
        sky: 'var(--color-sky)',
        'sky-depth': 'var(--color-sky-depth)',
        'sky-tint': 'var(--color-sky-tint)',
        'sky-text': 'var(--color-sky-text)',
        'sky-border': 'var(--color-sky-border)',
        'on-accent': 'var(--color-on-accent)',
        'disabled-bg': 'var(--color-disabled-bg)',
        'disabled-text': 'var(--color-disabled-text)',
        'disabled-depth': 'var(--color-disabled-depth)',
        'focus-ring': 'var(--color-focus-ring)',
        scrim: 'var(--color-scrim)',
        'coral-tint-2': 'var(--color-coral-tint-2)',
        'coral-text-2': 'var(--color-coral-text-2)',
        edge: 'var(--color-edge)',
        'board-a': 'var(--color-board-a)',
        'board-b': 'var(--color-board-b)',
        dashed: 'var(--color-dashed)',
      },
      fontFamily: {
        heading: ['Unbounded', '"Trebuchet MS"', 'sans-serif'],
        sans: ['Onest', '"Trebuchet MS"', 'sans-serif'],
        mono: ['ui-monospace', 'Menlo', 'monospace'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '58px', fontWeight: '700' }],
        'display-mobile': ['31px', { lineHeight: '40px', fontWeight: '700' }],
        h1: ['31px', { lineHeight: '40px', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '32px', fontWeight: '700' }],
        h3: ['19px', { lineHeight: '27px', fontWeight: '700' }],
        'body-l': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        body: ['16px', { lineHeight: '24px', fontWeight: '500' }],
        small: ['14px', { lineHeight: '20px', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '700' }],
        button: ['16px', { lineHeight: '22px', fontWeight: '700' }],
      },
      borderRadius: {
        input: '12px',
        control: '14px',
        card: '16px',
        chapter: '18px',
        reply: '20px',
        panel: '24px',
        pill: '999px',
      },
      borderWidth: { DEFAULT: '2px', 3: '3px' },
      boxShadow: {
        shashka: '4px 4px 0 var(--color-edge)',
        'shashka-lg': '6px 6px 0 var(--color-edge)',
        none: 'none',
      },
      translate: { press: '4px' },
      transitionTimingFunction: {
        spring: 'cubic-bezier(.34,1.56,.64,1)',
        out: 'cubic-bezier(.2,.8,.2,1)',
      },
      transitionDuration: { press: '120ms', pop: '220ms' },
      spacing: { sidebar: '264px', 'sidebar-compact': '88px', topbar: '88px' },
      maxWidth: { board: '720px' },
    },
  },
  plugins: [],
};

/* Пример «шашки»: className="border-2 border-edge shadow-shashka active:translate-x-press active:translate-y-press active:shadow-none" */
