// Generated by tools/generate-mascot-rig.mjs from the design package (shared/assets/cat/cat-rig.svg).
// Do not edit by hand.
import type { RigNode } from './types.js';

export const RIM = '$rim';

export const RIG: RigNode[] = [
  {
    tag: 'ellipse',
    attrs: {
      'data-layer': 'shadow',
      cx: '100',
      cy: '192',
      rx: '52',
      ry: '6',
      fill: '#1E1A2F',
      opacity: '0.12',
    },
  },
  {
    tag: 'g',
    attrs: {},
    children: [
      {
        tag: 'g',
        attrs: {
          transform: 'translate(0,0)',
          'data-layer': 'jump',
        },
        children: [
          {
            tag: 'g',
            attrs: {
              'data-layer': 'tail',
              'data-state': 'tail-up',
              display: 'inline',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M134 170 C 172 174, 186 146, 176 122 C 172 112, 163 111, 161 119',
                  fill: 'none',
                  stroke: '$rim',
                  strokeWidth: '19',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M134 170 C 172 174, 186 146, 176 122 C 172 112, 163 111, 161 119',
                  fill: 'none',
                  stroke: '#1E1A2F',
                  strokeWidth: '14',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M169 113 C 165 110, 161 113, 161 119',
                  fill: 'none',
                  stroke: '#FFFFFF',
                  strokeWidth: '14',
                  strokeLinecap: 'round',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'tail',
              'data-state': 'tail-wrap',
              display: 'none',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M136 172 C 128 194, 76 196, 60 182',
                  fill: 'none',
                  stroke: '$rim',
                  strokeWidth: '19',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M136 172 C 128 194, 76 196, 60 182',
                  fill: 'none',
                  stroke: '#1E1A2F',
                  strokeWidth: '14',
                  strokeLinecap: 'round',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'body',
            },
            children: [
              {
                tag: 'ellipse',
                attrs: {
                  cx: '100',
                  cy: '158',
                  rx: '44',
                  ry: '34',
                  fill: '#1E1A2F',
                  stroke: '$rim',
                  strokeWidth: '3',
                },
              },
              {
                tag: 'ellipse',
                attrs: {
                  cx: '100',
                  cy: '160',
                  rx: '22',
                  ry: '26',
                  fill: '#FFFFFF',
                  'data-layer': 'chest',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'paws',
            },
            children: [
              {
                tag: 'ellipse',
                attrs: {
                  cx: '80',
                  cy: '187',
                  rx: '14',
                  ry: '8',
                  fill: '#FFFFFF',
                  stroke: '$rim',
                  strokeWidth: '2',
                },
              },
              {
                tag: 'ellipse',
                attrs: {
                  cx: '120',
                  cy: '187',
                  rx: '14',
                  ry: '8',
                  fill: '#FFFFFF',
                  stroke: '$rim',
                  strokeWidth: '2',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M76 184 v5 M84 184 v5 M116 184 v5 M124 184 v5',
                  stroke: '#D9D4EE',
                  strokeWidth: '2',
                  strokeLinecap: 'round',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'head',
              transform: 'rotate(-4 100 130)',
            },
            children: [
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'ears',
                },
                children: [
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M48 72 L 56 22 L 88 44 Z',
                      fill: '#1E1A2F',
                      stroke: '$rim',
                      strokeWidth: '7',
                      strokeLinejoin: 'round',
                    },
                  },
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M152 72 L 144 22 L 112 44 Z',
                      fill: '#1E1A2F',
                      stroke: '$rim',
                      strokeWidth: '7',
                      strokeLinejoin: 'round',
                    },
                  },
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M57 58 L 61 34 L 79 47 Z',
                      fill: '#FF9DB5',
                      stroke: '#FF9DB5',
                      strokeWidth: '4',
                      strokeLinejoin: 'round',
                    },
                  },
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M143 58 L 139 34 L 121 47 Z',
                      fill: '#FF9DB5',
                      stroke: '#FF9DB5',
                      strokeWidth: '4',
                      strokeLinejoin: 'round',
                    },
                  },
                ],
              },
              {
                tag: 'ellipse',
                attrs: {
                  cx: '100',
                  cy: '82',
                  rx: '60',
                  ry: '50',
                  fill: '#1E1A2F',
                  stroke: '$rim',
                  strokeWidth: '3',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M100 44 C 94 44, 93 62, 92 80 C 76 84, 68 98, 74 110 C 82 123, 118 123, 126 110 C 132 98, 124 84, 108 80 C 107 62, 106 44, 100 44 Z',
                  fill: '#FFFFFF',
                },
              },
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'whiskers',
                  'data-state': 'whiskers',
                  display: 'inline',
                  stroke: '#C9C3E3',
                  strokeWidth: '2',
                  strokeLinecap: 'round',
                },
                children: [
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M72 101 L 46 96 M72 107 L 47 110 M128 101 L 154 96 M128 107 L 153 110',
                    },
                  },
                ],
              },
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'blush',
                  'data-state': 'blush',
                  display: 'none',
                },
                children: [
                  {
                    tag: 'ellipse',
                    attrs: {
                      cx: '62',
                      cy: '99',
                      rx: '7',
                      ry: '4',
                      fill: '#FF9DB5',
                      opacity: '0.6',
                    },
                  },
                  {
                    tag: 'ellipse',
                    attrs: {
                      cx: '138',
                      cy: '99',
                      rx: '7',
                      ry: '4',
                      fill: '#FF9DB5',
                      opacity: '0.6',
                    },
                  },
                ],
              },
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'eyes',
                },
                children: [
                  {
                    tag: 'g',
                    attrs: {
                      'data-state': 'eyes-open',
                      display: 'inline',
                    },
                    children: [
                      {
                        tag: 'ellipse',
                        attrs: {
                          cx: '76',
                          cy: '80',
                          rx: '13',
                          ry: '14',
                          fill: '#FFC83D',
                        },
                      },
                      {
                        tag: 'ellipse',
                        attrs: {
                          cx: '124',
                          cy: '80',
                          rx: '13',
                          ry: '14',
                          fill: '#FFC83D',
                        },
                      },
                      {
                        tag: 'g',
                        attrs: {
                          transform: 'translate(0,0)',
                          'data-layer': 'pupils',
                        },
                        children: [
                          {
                            tag: 'ellipse',
                            attrs: {
                              cx: '77',
                              cy: '82',
                              rx: '6',
                              ry: '9',
                              fill: '#1E1A2F',
                            },
                          },
                          {
                            tag: 'ellipse',
                            attrs: {
                              cx: '125',
                              cy: '82',
                              rx: '6',
                              ry: '9',
                              fill: '#1E1A2F',
                            },
                          },
                          {
                            tag: 'circle',
                            attrs: {
                              cx: '80.5',
                              cy: '76',
                              r: '3.5',
                              fill: '#FFFFFF',
                            },
                          },
                          {
                            tag: 'circle',
                            attrs: {
                              cx: '128.5',
                              cy: '76',
                              r: '3.5',
                              fill: '#FFFFFF',
                            },
                          },
                          {
                            tag: 'circle',
                            attrs: {
                              cx: '74',
                              cy: '87',
                              r: '1.6',
                              fill: '#FFFFFF',
                            },
                          },
                          {
                            tag: 'circle',
                            attrs: {
                              cx: '122',
                              cy: '87',
                              r: '1.6',
                              fill: '#FFFFFF',
                            },
                          },
                        ],
                      },
                    ],
                  },
                  {
                    tag: 'g',
                    attrs: {
                      'data-state': 'eyes-happy',
                      display: 'none',
                      fill: 'none',
                      stroke: '#FFC83D',
                      strokeWidth: '5',
                      strokeLinecap: 'round',
                    },
                    children: [
                      {
                        tag: 'path',
                        attrs: {
                          d: 'M64 85 Q 76 70 88 85',
                        },
                      },
                      {
                        tag: 'path',
                        attrs: {
                          d: 'M112 85 Q 124 70 136 85',
                        },
                      },
                    ],
                  },
                  {
                    tag: 'g',
                    attrs: {
                      'data-state': 'eyes-closed',
                      display: 'none',
                      fill: 'none',
                      stroke: '#FFC83D',
                      strokeWidth: '4',
                      strokeLinecap: 'round',
                    },
                    children: [
                      {
                        tag: 'path',
                        attrs: {
                          d: 'M64 80 Q 76 90 88 80',
                        },
                      },
                      {
                        tag: 'path',
                        attrs: {
                          d: 'M112 80 Q 124 90 136 80',
                        },
                      },
                    ],
                  },
                  {
                    tag: 'g',
                    attrs: {
                      'data-state': 'eyes-proud',
                      display: 'none',
                    },
                    children: [
                      {
                        tag: 'path',
                        attrs: {
                          d: 'M63 79 L 89 79 Q 89 94 76 94 Q 63 94 63 79 Z',
                          fill: '#FFC83D',
                        },
                      },
                      {
                        tag: 'path',
                        attrs: {
                          d: 'M111 79 L 137 79 Q 137 94 124 94 Q 111 94 111 79 Z',
                          fill: '#FFC83D',
                        },
                      },
                      {
                        tag: 'circle',
                        attrs: {
                          cx: '77',
                          cy: '86',
                          r: '5',
                          fill: '#1E1A2F',
                        },
                      },
                      {
                        tag: 'circle',
                        attrs: {
                          cx: '125',
                          cy: '86',
                          r: '5',
                          fill: '#1E1A2F',
                        },
                      },
                      {
                        tag: 'circle',
                        attrs: {
                          cx: '79',
                          cy: '84',
                          r: '1.8',
                          fill: '#FFFFFF',
                        },
                      },
                      {
                        tag: 'circle',
                        attrs: {
                          cx: '127',
                          cy: '84',
                          r: '1.8',
                          fill: '#FFFFFF',
                        },
                      },
                      {
                        tag: 'path',
                        attrs: {
                          d: 'M61 78 L 91 78 M109 78 L 139 78',
                          stroke: '#7A70C2',
                          strokeWidth: '3',
                          strokeLinecap: 'round',
                        },
                      },
                    ],
                  },
                ],
              },
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'brows',
                  'data-state': 'brows',
                  display: 'none',
                  fill: 'none',
                  stroke: '#8C84B8',
                  strokeWidth: '4',
                  strokeLinecap: 'round',
                },
                children: [
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M63 63 Q 74 60 86 55',
                    },
                  },
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M137 63 Q 126 60 114 55',
                    },
                  },
                ],
              },
              {
                tag: 'path',
                attrs: {
                  'data-layer': 'nose',
                  d: 'M94 96 L 106 96 L 100 103 Z',
                  fill: '#FF9DB5',
                  stroke: '#FF9DB5',
                  strokeWidth: '3',
                  strokeLinejoin: 'round',
                },
              },
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'mouth',
                  fill: 'none',
                  stroke: '#1E1A2F',
                  strokeWidth: '3',
                  strokeLinecap: 'round',
                  strokeLinejoin: 'round',
                },
                children: [
                  {
                    tag: 'path',
                    attrs: {
                      'data-state': 'mouth-w',
                      display: 'inline',
                      d: 'M89 104 Q 94.5 111 100 104 Q 105.5 111 111 104',
                    },
                  },
                  {
                    tag: 'g',
                    attrs: {
                      'data-state': 'mouth-open',
                      display: 'none',
                    },
                    children: [
                      {
                        tag: 'path',
                        attrs: {
                          d: 'M88 104 Q 100 124 112 104 Z',
                          fill: '#1E1A2F',
                        },
                      },
                      {
                        tag: 'ellipse',
                        attrs: {
                          cx: '100',
                          cy: '113',
                          rx: '6',
                          ry: '3.5',
                          fill: '#FF9DB5',
                          stroke: 'none',
                        },
                      },
                    ],
                  },
                  {
                    tag: 'path',
                    attrs: {
                      'data-state': 'mouth-flat',
                      display: 'none',
                      d: 'M94 108 Q 100 110 106 108',
                    },
                  },
                  {
                    tag: 'path',
                    attrs: {
                      'data-state': 'mouth-wavy',
                      display: 'none',
                      d: 'M91 109 Q 95.5 104 100 109 Q 104.5 114 109 109',
                    },
                  },
                ],
              },
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'acc-glasses',
                  'data-state': 'acc-glasses',
                  display: 'none',
                  fill: 'none',
                  stroke: '#FFFFFF',
                  strokeWidth: '4',
                  strokeLinecap: 'round',
                },
                children: [
                  {
                    tag: 'circle',
                    attrs: {
                      cx: '76',
                      cy: '80',
                      r: '17',
                    },
                  },
                  {
                    tag: 'circle',
                    attrs: {
                      cx: '124',
                      cy: '80',
                      r: '17',
                    },
                  },
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M93 78 Q 100 72 107 78 M59 76 L 46 70 M141 76 L 154 70',
                    },
                  },
                ],
              },
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'acc-crown',
                  'data-state': 'acc-crown',
                  display: 'none',
                },
                children: [
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M76 42 L 73 16 L 88 28 L 100 10 L 112 28 L 127 16 L 124 42 Z',
                      fill: '#FFC83D',
                      stroke: '#E0A800',
                      strokeWidth: '3',
                      strokeLinejoin: 'round',
                    },
                  },
                  {
                    tag: 'circle',
                    attrs: {
                      cx: '100',
                      cy: '32',
                      r: '4',
                      fill: '#FF8F6B',
                    },
                  },
                  {
                    tag: 'circle',
                    attrs: {
                      cx: '86',
                      cy: '36',
                      r: '3',
                      fill: '#38B6FF',
                    },
                  },
                  {
                    tag: 'circle',
                    attrs: {
                      cx: '114',
                      cy: '36',
                      r: '3',
                      fill: '#2ED47A',
                    },
                  },
                ],
              },
              {
                tag: 'g',
                attrs: {
                  'data-layer': 'acc-hat',
                  'data-state': 'acc-hat',
                  display: 'none',
                },
                children: [
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M58 46 Q 100 -8 142 46 Z',
                      fill: '#FF8F6B',
                      stroke: '#E56F4A',
                      strokeWidth: '3',
                      strokeLinejoin: 'round',
                    },
                  },
                  {
                    tag: 'path',
                    attrs: {
                      d: 'M78 34 L 86 20 M100 30 L 100 12 M122 34 L 114 20',
                      stroke: '#FFFFFF',
                      strokeWidth: '3',
                      strokeLinecap: 'round',
                      opacity: '0.7',
                    },
                  },
                  {
                    tag: 'rect',
                    attrs: {
                      x: '54',
                      y: '38',
                      width: '92',
                      height: '14',
                      rx: '7',
                      fill: '#FFFFFF',
                      stroke: '#E4E0F5',
                      strokeWidth: '2',
                    },
                  },
                  {
                    tag: 'circle',
                    attrs: {
                      cx: '100',
                      cy: '8',
                      r: '9',
                      fill: '#FFFFFF',
                      stroke: '#E4E0F5',
                      strokeWidth: '2',
                    },
                  },
                ],
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'bowtie',
              'data-state': 'bowtie',
              display: 'inline',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M100 132 L 80 122 L 80 142 Z',
                  fill: '#5B4BFF',
                  stroke: '#5B4BFF',
                  strokeWidth: '5',
                  strokeLinejoin: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M100 132 L 120 122 L 120 142 Z',
                  fill: '#5B4BFF',
                  stroke: '#5B4BFF',
                  strokeWidth: '5',
                  strokeLinejoin: 'round',
                },
              },
              {
                tag: 'rect',
                attrs: {
                  x: '83',
                  y: '127',
                  width: '5',
                  height: '5',
                  fill: '#FFFFFF',
                  opacity: '0.55',
                },
              },
              {
                tag: 'rect',
                attrs: {
                  x: '88',
                  y: '132',
                  width: '5',
                  height: '5',
                  fill: '#FFFFFF',
                  opacity: '0.55',
                },
              },
              {
                tag: 'rect',
                attrs: {
                  x: '83',
                  y: '137',
                  width: '4',
                  height: '4',
                  fill: '#FFFFFF',
                  opacity: '0.55',
                },
              },
              {
                tag: 'rect',
                attrs: {
                  x: '112',
                  y: '127',
                  width: '5',
                  height: '5',
                  fill: '#FFFFFF',
                  opacity: '0.55',
                },
              },
              {
                tag: 'rect',
                attrs: {
                  x: '107',
                  y: '132',
                  width: '5',
                  height: '5',
                  fill: '#FFFFFF',
                  opacity: '0.55',
                },
              },
              {
                tag: 'rect',
                attrs: {
                  x: '113',
                  y: '137',
                  width: '4',
                  height: '4',
                  fill: '#FFFFFF',
                  opacity: '0.55',
                },
              },
              {
                tag: 'rect',
                attrs: {
                  x: '93',
                  y: '125',
                  width: '14',
                  height: '14',
                  rx: '4',
                  fill: '#4335D6',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'acc-scarf',
              'data-state': 'acc-scarf',
              display: 'none',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M60 124 Q 100 146 140 124 L 140 138 Q 100 160 60 138 Z',
                  fill: '#38B6FF',
                  stroke: '#1A93DB',
                  strokeWidth: '2.5',
                  strokeLinejoin: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M118 140 L 128 174 L 112 176 L 106 144 Z',
                  fill: '#38B6FF',
                  stroke: '#1A93DB',
                  strokeWidth: '2.5',
                  strokeLinejoin: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M76 134 L 80 144 M96 138 L 98 148 M116 136 L 114 146 M114 160 L 126 158',
                  stroke: '#FFFFFF',
                  strokeWidth: '3',
                  strokeLinecap: 'round',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'acc-medal',
              'data-state': 'acc-medal',
              display: 'none',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M88 136 L 96 158 M112 136 L 104 158',
                  stroke: '#5B4BFF',
                  strokeWidth: '6',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'circle',
                attrs: {
                  cx: '100',
                  cy: '166',
                  r: '12',
                  fill: '#FFC83D',
                  stroke: '#E0A800',
                  strokeWidth: '3',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M100 159 l2.2 4.4 4.8.7-3.5 3.4.8 4.8-4.3-2.3-4.3 2.3.8-4.8-3.5-3.4 4.8-.7z',
                  fill: '#FFFFFF',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'paws',
              'data-state': 'paw-wave',
              display: 'none',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M130 148 L 158 110',
                  stroke: '$rim',
                  strokeWidth: '20',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M130 148 L 158 110',
                  stroke: '#1E1A2F',
                  strokeWidth: '15',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'circle',
                attrs: {
                  cx: '160',
                  cy: '105',
                  r: '10',
                  fill: '#FFFFFF',
                  stroke: '$rim',
                  strokeWidth: '2',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M175 90 Q 181 97 177 106 M183 84 Q 191 96 185 110',
                  fill: 'none',
                  stroke: '#5B4BFF',
                  strokeWidth: '3',
                  strokeLinecap: 'round',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'paws',
              'data-state': 'paws-up',
              display: 'none',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M70 148 L 40 108 M130 148 L 160 108',
                  stroke: '$rim',
                  strokeWidth: '20',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M70 148 L 40 108 M130 148 L 160 108',
                  stroke: '#1E1A2F',
                  strokeWidth: '15',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'circle',
                attrs: {
                  cx: '38',
                  cy: '103',
                  r: '10',
                  fill: '#FFFFFF',
                  stroke: '$rim',
                  strokeWidth: '2',
                },
              },
              {
                tag: 'circle',
                attrs: {
                  cx: '162',
                  cy: '103',
                  r: '10',
                  fill: '#FFFFFF',
                  stroke: '$rim',
                  strokeWidth: '2',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'paws',
              'data-state': 'paw-chin',
              display: 'none',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M128 152 L 122 124',
                  stroke: '$rim',
                  strokeWidth: '20',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M128 152 L 122 124',
                  stroke: '#1E1A2F',
                  strokeWidth: '15',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'circle',
                attrs: {
                  cx: '120',
                  cy: '119',
                  r: '10',
                  fill: '#FFFFFF',
                  stroke: '$rim',
                  strokeWidth: '2',
                },
              },
            ],
          },
          {
            tag: 'g',
            attrs: {
              'data-layer': 'paws',
              'data-state': 'paw-hint',
              display: 'none',
            },
            children: [
              {
                tag: 'path',
                attrs: {
                  d: 'M130 148 L 150 104',
                  stroke: '$rim',
                  strokeWidth: '20',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'path',
                attrs: {
                  d: 'M130 148 L 150 104',
                  stroke: '#1E1A2F',
                  strokeWidth: '15',
                  strokeLinecap: 'round',
                },
              },
              {
                tag: 'circle',
                attrs: {
                  cx: '151',
                  cy: '99',
                  r: '10',
                  fill: '#FFFFFF',
                  stroke: '$rim',
                  strokeWidth: '2',
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    tag: 'g',
    attrs: {
      'data-layer': 'fx-bulb',
      'data-state': 'fx-bulb',
      display: 'none',
    },
    children: [
      {
        tag: 'path',
        attrs: {
          d: 'M168 16 L 168 10 M150 24 L 145 20 M186 24 L 191 20',
          stroke: '#E0A800',
          strokeWidth: '3',
          strokeLinecap: 'round',
        },
      },
      {
        tag: 'circle',
        attrs: {
          cx: '168',
          cy: '38',
          r: '14',
          fill: '#FFC83D',
          stroke: '#E0A800',
          strokeWidth: '3',
        },
      },
      {
        tag: 'rect',
        attrs: {
          x: '161',
          y: '51',
          width: '14',
          height: '10',
          rx: '3',
          fill: '#B7B2D6',
        },
      },
      {
        tag: 'path',
        attrs: {
          d: 'M164 38 Q 168 32 172 38',
          fill: 'none',
          stroke: '#FFFFFF',
          strokeWidth: '2.5',
          strokeLinecap: 'round',
        },
      },
    ],
  },
  {
    tag: 'g',
    attrs: {
      'data-layer': 'fx-think',
      'data-state': 'fx-think',
      display: 'none',
      fill: '#B7B2D6',
    },
    children: [
      {
        tag: 'circle',
        attrs: {
          cx: '40',
          cy: '44',
          r: '5',
        },
      },
      {
        tag: 'circle',
        attrs: {
          cx: '28',
          cy: '30',
          r: '7',
        },
      },
      {
        tag: 'circle',
        attrs: {
          cx: '14',
          cy: '12',
          r: '9',
        },
      },
    ],
  },
  {
    tag: 'g',
    attrs: {
      'data-layer': 'fx-zzz',
      'data-state': 'fx-zzz',
      display: 'none',
      fill: 'none',
      stroke: '#8577FF',
      strokeWidth: '3.5',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    children: [
      {
        tag: 'path',
        attrs: {
          d: 'M150 30 h12 l-12 13 h12',
        },
      },
      {
        tag: 'path',
        attrs: {
          d: 'M170 12 h9 l-9 10 h9',
        },
      },
    ],
  },
  {
    tag: 'g',
    attrs: {
      'data-layer': 'fx-confetti',
      'data-state': 'fx-confetti',
      display: 'none',
    },
    children: [
      {
        tag: 'rect',
        attrs: {
          x: '20',
          y: '30',
          width: '10',
          height: '6',
          rx: '2',
          fill: '#FFC83D',
          transform: 'rotate(-25 25 33)',
        },
      },
      {
        tag: 'rect',
        attrs: {
          x: '170',
          y: '40',
          width: '10',
          height: '6',
          rx: '2',
          fill: '#2ED47A',
          transform: 'rotate(30 175 43)',
        },
      },
      {
        tag: 'rect',
        attrs: {
          x: '40',
          y: '10',
          width: '8',
          height: '5',
          rx: '2',
          fill: '#38B6FF',
          transform: 'rotate(15 44 12)',
        },
      },
      {
        tag: 'rect',
        attrs: {
          x: '150',
          y: '12',
          width: '9',
          height: '5',
          rx: '2',
          fill: '#FF8F6B',
          transform: 'rotate(-20 154 14)',
        },
      },
      {
        tag: 'circle',
        attrs: {
          cx: '182',
          cy: '70',
          r: '4',
          fill: '#5B4BFF',
        },
      },
      {
        tag: 'circle',
        attrs: {
          cx: '14',
          cy: '64',
          r: '4',
          fill: '#FF9DB5',
        },
      },
      {
        tag: 'circle',
        attrs: {
          cx: '100',
          cy: '6',
          r: '3.5',
          fill: '#2ED47A',
        },
      },
    ],
  },
  {
    tag: 'g',
    attrs: {
      'data-layer': 'fx-sparkle',
      'data-state': 'fx-sparkle',
      display: 'none',
      fill: '#FFC83D',
    },
    children: [
      {
        tag: 'path',
        attrs: {
          d: 'M162 128 Q 164 138 174 140 Q 164 142 162 152 Q 160 142 150 140 Q 160 138 162 128 Z',
        },
      },
      {
        tag: 'path',
        attrs: {
          d: 'M36 124 Q 37 130 43 131 Q 37 132 36 138 Q 35 132 29 131 Q 35 130 36 124 Z',
        },
      },
    ],
  },
];
